### PR TITLE
Define the dry-struct so as to avoid metadata

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made? 🤔

The old way made introspection impossible:

```
node = Cocina::Models::DescriptiveValue.schema.find { |key| key.name == :source }
node.type
node.type.right
#<Class:0x000000010ae7f710>
```

## How was this change tested? 🤨
Added a unit test.

### CODE REVIEW

**Review by justinlittman — COMMENTED** [review]
Is this going to break everything?

**Comment by jcoyne** [comment]
@justinlittman I don't know.  The tests here seem to pass.

**Comment by justinlittman** [comment]
If we've learned anything, it is that the tests passing means nothing about our actual data.

Running a validation report. I'll let you know what it finds.

**Comment by justinlittman** [comment]
Can you test branch against DSA and Argo?

**Comment by jcoyne** [comment]
Both Argo (https://github.com/sul-dlss/argo/pull/3517) and DSA (https://github.com/sul-dlss/dor-services-app/pull/3889) don't seem to have problems with this change.

**Review by justinlittman — APPROVED** [review]

**Pull request merged**
