### PR TITLE
Move hasAgreement to AdminPolicy

### LINKED ISSUE #259: DROStructural:  no agreements, only APOs have them.  APOs should REQUIRE agreementId
1.  Currently DROStructural contains "hasAgreement" but per @andrewjbtw:

> items don’t need to have agreements anywhere
> the reference back to agreements is just supposed to be in the APO RELS-EXT

2. require agreementId for AdminPolicy objects (in adminPolicyAdminstrative as "referencesAgreement" )

### PR DESCRIPTION
**Pull request by jcoyne**
**NOTE:  Changes to openapi.yml require updating openapi.yml for sdr-api and dor-services-app and generating models - see README.**

## Why was this change made?
Fixes #259

### CODE REVIEW

**Review by justinlittman — CHANGES_REQUESTED** [review]
So this requires `hasAgreement`. However, the ticket suggests Honeybadger alerting when an APO is missing an agreement, suggesting that some APOS do not have agreements. Is that going to be a problem?

**Comment by justinlittman** [comment]
P.S. That is my only issue with this PR. Otherwise, I approve.

**Comment by jcoyne** [comment]
@justinlittman item 2 and item 3 on that issue seem to be contradictory.  What do you think we should do?

**Comment by justinlittman** [comment]
We could write a report to check if there are APOs missing an agreement and then decide to remediate or lax enforce.

**Comment by justinlittman** [comment]
https://github.com/sul-dlss/dor-services-app/issues/3142 is for the report.

**Review by justinlittman — APPROVED** [review]

**Pull request merged**
