### PR TITLE
Generate without depending on rubocop for formatting

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?

Less noise in the output

## How was this change tested?
Test suite

## Which documentation and/or configurations were updated?

n/a

### CODE REVIEW

**Comment by jcoyne** [comment]
@justinlittman it was just a lot of noise and made the output less useful.   How did you get burned before?

**Comment by justinlittman** [comment]
I was spending a lot of time fiddling with spaces trying to get the layout right. I'd argue that worrying about formatting in code makes the code harder to understand / change, albeit at the expense of more noisy output.

To be clear, this represents my opinion, not a hard change requirement on this ticket.

**Comment by mjgiarlo** [comment]
@jcoyne @justinlittman How about this alternative approach? https://github.com/sul-dlss/cocina-models/pull/161

**Comment by mjgiarlo** [comment]
@jcoyne shall we close this now that #161 is merged? thanks for working to make our tools kinder to us

**Pull request closed without merging**
