### PR TITLE
Generate models en masse and run rubocop en masse

### PR DESCRIPTION
**Pull request by mjgiarlo**
## Why was this change made? 🤔

This commit speeds up model generation notably by significantly reducing the number of times we have to run rubocop, which is now down to one time.

## How was this change tested? 🤨

CI + repeated generation runs

### CODE REVIEW

**Review by jcoyne — COMMENTED** [review]
Does this still work even if you're only generating a single schema?

**Comment by mjgiarlo** [comment]
@jcoyne 💬 
> Does this still work even if you're only generating a single schema (e.g. `exe/generator generate_schema DRO`)?

Yes, but that bit is jammed into another commit (pulling these small PRs out of another branch). I'll grab that. Good eye!

**Review by jcoyne — APPROVED** [review]

**Review by ndushay — APPROVED** [review]
this seems like an annoying weird hoop for using rubocop.

**Comment by mjgiarlo** [comment]
@ndushay 💬 
> this seems like an annoying weird hoop for using rubocop.

On one hand, yeah. On the other, it's also nice to generate models w/o caring too much about indentation and whitespace and then fixing it all up in one fell swoop at the end.

**Comment by justinlittman** [comment]
Yeah, the motivation behind the rubocop cleanup is that it was nearly impossible to get the indentation and whitespace correct when generating.

**Pull request merged**
