### PR TITLE
Descriptive

### PR DESCRIPTION
**Pull request by jcoyne**
Note: this currently fails to generate because we don't yet support `allOf`

### CODE REVIEW

**Comment by justinlittman** [comment]
@jcoyne Can you provide some more context / description for the ticket? It's hard to understand solely from the openapi changes.

**Comment by jcoyne** [comment]
@justinlittman this is the plan for descriptive metadata that Arcadia has given me.

**Comment by justinlittman** [comment]
@jcoyne I understand that. Is it described / documented anywhere? (other than the openapi).

**Comment by justinlittman** [comment]
Some examples?

**Comment by jcoyne** [comment]
I'll ask Arcadia to give you access.

**Pull request closed without merging**
